import "./globals.css";
import type { Metadata } from "next";
import Model from "@/components/Model";

export const metadata: Metadata = {
  title: "Trello clone",
  description: "Generated by QAISS, credit sonny sangha",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        {children}
        <Model />
      </body>
    </html>
  );
}
